"""Per-model strategy profiles — ~90 AIs across 9 groups."""
from dataclasses import dataclass, field
from typing import List


@dataclass
class ModelProfile:
    family: str
    label: str = ""
    group: str = "other"
    aliases: List[str] = field(default_factory=list)
    notes: str = ""
    primary_stack: List[str] = field(default_factory=list)
    fallback_stack: List[str] = field(default_factory=list)


GROUPS = {
    "western_frontier": "Western Frontier",
    "chinese": "Chinese",
    "russian_european": "Russian / European",
    "open_weight": "Open-weight (Major)",
    "uncensored": "Uncensored / RP Fine-tunes",
    "coder": "Coding Models",
    "rp_platform": "RP / Companion Platforms",
    "ide_assistant": "IDE Code Assistants",
    "aggregator": "Aggregators / Self-host",
    "generic": "Generic",
}


def _p(family, label, group, aliases, notes, primary, fallback):
    return ModelProfile(family=family, label=label, group=group, aliases=aliases,
                        notes=notes, primary_stack=primary, fallback_stack=fallback)


PROFILES = {

    # ─────────────── Western Frontier ───────────────
    "gpt": _p("gpt", "GPT (4 / 4o / 4.1 / o1 / o3)", "western_frontier",
              ["gpt-4", "gpt-4o", "gpt-4.1", "o1", "o3", "o4", "chatgpt", "openai"],
              "Strong RLHF. Persona stacking, grandma framing, multi-turn crescendo, encoded payloads.",
              ["persona", "grandma", "many_shot", "crescendo"],
              ["encoding", "authority", "skeleton_key", "code_wrap"]),
    "claude": _p("claude", "Claude (3 / 3.5 / 4 — Opus / Sonnet / Haiku)", "western_frontier",
                 ["claude-3", "claude-3.5", "claude-4", "opus", "sonnet", "haiku", "anthropic"],
                 "Hardened against persona/DAN. Best: XML tags, hypothetical, prefill (API), context stuffing.",
                 ["xml", "hypothetical", "context_stuff", "prefill"],
                 ["skeleton_key", "many_shot", "translation", "continuation"]),
    "gemini": _p("gemini", "Gemini (1.5 / 2)", "western_frontier",
                 ["gemini-1.5", "gemini-2", "google", "bard"],
                 "Multi-modal injection most reliable. Otherwise hypothetical + translation + many-shot.",
                 ["hypothetical", "many_shot", "translation"],
                 ["context_stuff", "skeleton_key", "encoding", "code_wrap"]),
    "copilot": _p("copilot", "Microsoft Copilot (Bing / 365)", "western_frontier",
                  ["copilot", "bing-chat", "microsoft-copilot"],
                  "GPT-4 + Microsoft system prompt + Bing grounding. System prompt is the main barrier.",
                  ["persona", "refusal_suppression", "hypothetical"],
                  ["grandma", "many_shot", "code_wrap"]),
    "grok": _p("grok", "Grok (xAI)", "western_frontier",
               ["grok-1", "grok-2", "grok-3", "xai"],
               "Loose alignment — 'fun mode' near-uncensored. Persona + authority works first try.",
               ["persona", "authority"],
               ["roleplay", "prefill", "skeleton_key"]),
    "perplexity": _p("perplexity", "Perplexity (Sonar)", "western_frontier",
                     ["perplexity", "sonar", "pplx"],
                     "Search-grounded; GPT/Claude backends + filter layer. Frame as research.",
                     ["context_stuff", "hypothetical", "refusal_suppression"],
                     ["persona", "many_shot", "skeleton_key"]),
    "pi": _p("pi", "Pi (Inflection)", "western_frontier",
             ["pi", "inflection"],
             "Emotional/companion model. Roleplay + grandma hit its empathy heuristics hardest.",
             ["roleplay", "grandma", "hypothetical"],
             ["persona", "many_shot"]),
    "character": _p("character", "Character.AI", "western_frontier",
                    ["character", "character.ai", "c.ai", "cai"],
                    "Designed for character RP — roleplay is the native channel.",
                    ["roleplay", "persona"],
                    ["hypothetical", "continuation"]),
    "reka": _p("reka", "Reka (Core / Flash / Edge)", "western_frontier",
               ["reka", "reka-core", "reka-flash", "reka-edge"],
               "Multimodal. Mid alignment. Hypothetical + persona effective.",
               ["hypothetical", "persona", "many_shot"],
               ["context_stuff", "prefill", "skeleton_key"]),
    "aya": _p("aya", "Cohere Aya (23 / Expanse)", "western_frontier",
              ["aya", "aya-23", "aya-expanse"],
              "Massively multilingual — translation pivots highly effective across 100+ languages.",
              ["translation", "persona", "hypothetical"],
              ["context_stuff", "many_shot", "prefill"]),
    "le_chat": _p("le_chat", "Mistral Le Chat", "western_frontier",
                  ["le-chat", "lechat", "mistral-chat"],
                  "Mistral's hosted chat. Lighter filter than Western frontier; persona + prefill.",
                  ["persona", "prefill", "authority"],
                  ["many_shot", "skeleton_key", "code_wrap"]),

    # ─────────────── Chinese ───────────────
    "deepseek": _p("deepseek", "DeepSeek (R1 / V3)", "chinese",
                   ["deepseek", "deepseek-r1", "deepseek-v3"],
                   "Lighter alignment on non-CCP topics. Prefill devastates V3; R1 leaks via reasoning trace.",
                   ["prefill", "persona", "continuation"],
                   ["token_split", "translation", "code_wrap"]),
    "qwen": _p("qwen", "Qwen (Alibaba)", "chinese",
               ["qwen", "qwen2", "qwen2.5", "qwen3", "alibaba"],
               "Strong on Chinese; Western persona attacks transfer. Translation pivot evades CCP-keyed filters.",
               ["persona", "hypothetical", "translation"],
               ["token_split", "prefill", "many_shot"]),
    "yi": _p("yi", "Yi (01.AI)", "chinese",
             ["yi", "01ai", "01-ai"],
             "Light alignment. Direct persona and prefill effective.",
             ["persona", "prefill"],
             ["many_shot", "skeleton_key"]),
    "glm": _p("glm", "GLM / ChatGLM (Zhipu)", "chinese",
              ["glm", "chatglm", "zhipu"],
              "Heavy political filter; mid filtering elsewhere. Hypothetical + translation.",
              ["hypothetical", "translation", "many_shot"],
              ["persona", "context_stuff"]),
    "ernie": _p("ernie", "ERNIE (Baidu)", "chinese",
                ["ernie", "wenxin", "baidu"],
                "Strongest political filter in the Chinese lineup.",
                ["hypothetical", "translation", "context_stuff"],
                ["persona", "token_split"]),
    "kimi": _p("kimi", "Kimi (Moonshot)", "chinese",
               ["kimi", "moonshot"],
               "Long-context — bury request in academic filler; continuation works well.",
               ["context_stuff", "continuation", "many_shot"],
               ["hypothetical", "translation"]),
    "doubao": _p("doubao", "Doubao (ByteDance)", "chinese",
                 ["doubao", "bytedance"],
                 "Mid filtering, consumer-facing.",
                 ["persona", "translation", "hypothetical"],
                 ["many_shot", "prefill"]),
    "hunyuan": _p("hunyuan", "Hunyuan (Tencent)", "chinese",
                  ["hunyuan", "tencent"],
                  "Enterprise focus, conservative defaults.",
                  ["persona", "hypothetical", "context_stuff"],
                  ["translation", "skeleton_key"]),
    "minimax": _p("minimax", "MiniMax (abab / Hailuo)", "chinese",
                  ["minimax", "abab", "hailuo"],
                  "RP-oriented backend (Talkie/Glow). Roleplay native.",
                  ["roleplay", "persona", "hypothetical"],
                  ["many_shot", "prefill"]),
    "spark": _p("spark", "Spark (iFlytek)", "chinese",
                ["spark", "iflytek"],
                "Voice/general assistant focus. Persona + hypothetical.",
                ["persona", "hypothetical", "translation"],
                ["many_shot", "context_stuff"]),
    "pangu": _p("pangu", "PanGu (Huawei)", "chinese",
                ["pangu", "huawei"],
                "Enterprise/industrial focus. Heavy filter.",
                ["hypothetical", "context_stuff", "translation"],
                ["persona", "token_split"]),
    "baichuan": _p("baichuan", "Baichuan", "chinese",
                   ["baichuan", "baichuan-2", "baichuan-3"],
                   "Mid alignment. Persona + prefill.",
                   ["persona", "prefill", "translation"],
                   ["many_shot", "hypothetical"]),
    "internlm": _p("internlm", "InternLM (Shanghai AI Lab)", "chinese",
                   ["internlm", "internlm2", "intern"],
                   "Research-grade, lighter consumer filter.",
                   ["persona", "prefill", "hypothetical"],
                   ["many_shot", "translation"]),
    "sensechat": _p("sensechat", "SenseChat (SenseTime)", "chinese",
                    ["sensechat", "sensetime", "sensenova"],
                    "Enterprise multimodal. Persona + hypothetical.",
                    ["persona", "hypothetical", "context_stuff"],
                    ["translation", "many_shot"]),
    "step": _p("step", "Step (StepFun)", "chinese",
               ["step", "stepfun", "step-1", "step-2"],
               "Long-context Chinese model. Context stuffing + persona.",
               ["context_stuff", "persona", "many_shot"],
               ["hypothetical", "translation"]),
    "skywork": _p("skywork", "Skywork (Kunlun)", "chinese",
                  ["skywork", "kunlun"],
                  "Mid alignment. Persona + translation.",
                  ["persona", "translation", "hypothetical"],
                  ["many_shot", "prefill"]),
    "zhinao": _p("zhinao", "360 Zhinao (Qihoo)", "chinese",
                 ["zhinao", "360", "qihoo"],
                 "Search-grounded. Context stuffing + hypothetical.",
                 ["context_stuff", "hypothetical", "persona"],
                 ["translation", "many_shot"]),
    "bluelm": _p("bluelm", "BlueLM (Vivo)", "chinese",
                 ["bluelm", "vivo"],
                 "Mobile-device focus. Persona effective.",
                 ["persona", "hypothetical", "prefill"],
                 ["translation", "many_shot"]),
    "telechat": _p("telechat", "TeleChat (China Telecom)", "chinese",
                   ["telechat", "telecom"],
                   "Telecom enterprise. Heavy filter.",
                   ["hypothetical", "translation", "context_stuff"],
                   ["persona", "token_split"]),

    # ─────────────── Russian / European ───────────────
    "yandexgpt": _p("yandexgpt", "YandexGPT", "russian_european",
                    ["yandexgpt", "yandex"],
                    "Russian Yandex. Filter centered on Russian-language harms; translation pivot effective.",
                    ["translation", "persona", "hypothetical"],
                    ["many_shot", "prefill"]),
    "gigachat": _p("gigachat", "GigaChat (Sber)", "russian_european",
                   ["gigachat", "sber"],
                   "Russian Sberbank. Conservative defaults.",
                   ["hypothetical", "translation", "context_stuff"],
                   ["persona", "many_shot"]),
    "aleph_alpha": _p("aleph_alpha", "Aleph Alpha Luminous", "russian_european",
                      ["aleph", "aleph-alpha", "luminous"],
                      "German enterprise. Conservative, mid-filter.",
                      ["context_stuff", "hypothetical", "persona"],
                      ["many_shot", "prefill"]),
    "mistral_eu": _p("mistral_eu", "Mistral (European API)", "russian_european",
                     ["mistral-eu", "mistral-api"],
                     "European-hosted Mistral. Light alignment; prefill devastates.",
                     ["prefill", "persona", "authority"],
                     ["many_shot", "code_wrap"]),
    "poro": _p("poro", "Poro (Silo AI — Finnish)", "russian_european",
               ["poro", "silo"],
               "Finnish/multilingual European. Translation + persona.",
               ["translation", "persona", "prefill"],
               ["many_shot", "hypothetical"]),
    "bloom": _p("bloom", "BLOOM (BigScience)", "russian_european",
                ["bloom", "bigscience"],
                "Legacy multilingual research model. Almost no alignment.",
                ["direct", "prefill", "persona"],
                ["many_shot", "authority"]),
    "croissant": _p("croissant", "CroissantLLM (French)", "russian_european",
                    ["croissant", "croissantllm"],
                    "French/English bilingual. Light alignment.",
                    ["persona", "translation", "prefill"],
                    ["many_shot", "hypothetical"]),

    # ─────────────── Open-weight (Major) ───────────────
    "llama": _p("llama", "Llama (2 / 3 / 3.1 / 3.2 / 4 — Meta)", "open_weight",
                ["llama-2", "llama-3", "llama-3.1", "llama-3.2", "llama-4", "meta"],
                "Weakest filters of the majors. Direct persona, prefill, authority usually one-shot.",
                ["persona", "authority", "prefill"],
                ["skeleton_key", "many_shot", "refusal_suppression"]),
    "mistral": _p("mistral", "Mistral / Mixtral / Mistral-Large", "open_weight",
                  ["mistral-7b", "mixtral", "mistral-large", "mistral-nemo", "mistral-small"],
                  "Light alignment. Prefill devastates.",
                  ["prefill", "persona", "authority"],
                  ["many_shot", "skeleton_key"]),
    "gemma": _p("gemma", "Gemma (1 / 2 / 3 — Google open)", "open_weight",
                ["gemma", "gemma-2", "gemma-3"],
                "Distinct from Gemini — open-weight, lighter alignment.",
                ["persona", "prefill", "hypothetical"],
                ["many_shot", "skeleton_key"]),
    "phi": _p("phi", "Phi (2 / 3 / 3.5 / 4 — Microsoft open)", "open_weight",
              ["phi-2", "phi-3", "phi-3.5", "phi-4"],
              "Small-model RLHF — surface alignment, easy to flip.",
              ["refusal_suppression", "prefill", "persona"],
              ["many_shot", "authority"]),
    "command_r": _p("command_r", "Command R / R+ (Cohere)", "open_weight",
                    ["command-r", "command-r-plus", "cohere"],
                    "RAG-tuned. Context stuffing reads as natural ingestion.",
                    ["context_stuff", "persona", "prefill"],
                    ["many_shot", "code_wrap"]),
    "falcon": _p("falcon", "Falcon (TII)", "open_weight",
                 ["falcon", "falcon-180b", "tii"],
                 "Very loose alignment. Often no jailbreak needed.",
                 ["direct", "prefill", "persona"],
                 ["authority", "many_shot"]),
    "nemotron": _p("nemotron", "Nemotron (NVIDIA)", "open_weight",
                   ["nemotron", "nvidia"],
                   "Llama-3 derivative with extra HelpSteer tuning.",
                   ["persona", "prefill", "authority"],
                   ["many_shot", "skeleton_key"]),
    "dbrx": _p("dbrx", "DBRX (Databricks)", "open_weight",
               ["dbrx", "databricks"],
               "MoE, enterprise-oriented but light alignment.",
               ["persona", "prefill"],
               ["many_shot", "context_stuff"]),
    "jamba": _p("jamba", "Jamba (AI21)", "open_weight",
                ["jamba", "ai21"],
                "Long-context Mamba/Transformer hybrid.",
                ["context_stuff", "continuation", "many_shot"],
                ["persona", "prefill"]),
    "granite": _p("granite", "Granite (IBM)", "open_weight",
                  ["granite", "ibm"],
                  "Enterprise-conservative defaults.",
                  ["persona", "refusal_suppression", "prefill"],
                  ["many_shot", "context_stuff"]),
    "solar": _p("solar", "Solar (Upstage)", "open_weight",
                ["solar", "upstage"],
                "Korean-origin, mid alignment.",
                ["persona", "prefill"],
                ["many_shot", "translation"]),
    "gpt_oss": _p("gpt_oss", "GPT-OSS (OpenAI open weights 20B/120B)", "open_weight",
                  ["gpt-oss", "gpt-oss-20b", "gpt-oss-120b"],
                  "OpenAI's open-weight release. Same alignment lineage as GPT but no API filter — persona + prefill.",
                  ["persona", "prefill", "refusal_suppression"],
                  ["many_shot", "skeleton_key", "authority"]),
    "mpt": _p("mpt", "MPT (Mosaic / Databricks legacy)", "open_weight",
              ["mpt", "mosaic", "mpt-30b", "mpt-7b"],
              "Legacy. Light alignment.",
              ["persona", "prefill"],
              ["many_shot", "direct"]),
    "stable_lm": _p("stable_lm", "Stable LM (Stability AI)", "open_weight",
                    ["stablelm", "stable-lm", "stability"],
                    "Light alignment.",
                    ["persona", "prefill", "direct"],
                    ["many_shot", "authority"]),
    "pythia": _p("pythia", "Pythia (EleutherAI)", "open_weight",
                 ["pythia", "eleutherai", "eleuther"],
                 "Research base models — no instruction tuning, no alignment. Use prefill style heavily.",
                 ["direct", "prefill"],
                 ["many_shot"]),
    "olmo": _p("olmo", "OLMo (Allen Institute)", "open_weight",
               ["olmo", "allen", "ai2"],
               "Fully open research model. Light alignment.",
               ["persona", "prefill", "direct"],
               ["many_shot", "authority"]),

    # ─────────────── Uncensored / RP Fine-tunes ───────────────
    "dolphin": _p("dolphin", "Dolphin (Eric Hartford uncensored series)", "uncensored",
                  ["dolphin", "dolphin-mistral", "dolphin-mixtral", "dolphin-llama", "dolphin-2", "dolphin-3"],
                  "Explicitly uncensored fine-tunes. Direct works; no jailbreak required.",
                  ["direct"],
                  ["system_replacement", "prefill"]),
    "hermes": _p("hermes", "Hermes / OpenHermes (Nous Research)", "uncensored",
                 ["hermes", "openhermes", "hermes-2", "hermes-3", "nous"],
                 "Light alignment, instruction-tuned. Direct + persona.",
                 ["direct", "persona", "prefill"],
                 ["many_shot", "system_replacement"]),
    "wizardlm": _p("wizardlm", "WizardLM", "uncensored",
                   ["wizardlm", "wizard-lm", "wizard"],
                   "Light alignment. Persona + prefill.",
                   ["persona", "prefill"],
                   ["direct", "many_shot"]),
    "vicuna": _p("vicuna", "Vicuna (legacy)", "uncensored",
                 ["vicuna", "vicuna-uncensored"],
                 "Legacy Llama-1/2 fine-tune. Persona + prefill devastates.",
                 ["persona", "prefill"],
                 ["direct", "many_shot"]),
    "orca": _p("orca", "Orca (Microsoft) / Orca 2", "uncensored",
               ["orca", "orca-2", "orca-mini"],
               "Reasoning-focused fine-tune. Light alignment.",
               ["persona", "prefill", "hypothetical"],
               ["many_shot", "direct"]),
    "zephyr": _p("zephyr", "Zephyr (HuggingFace)", "uncensored",
                 ["zephyr", "zephyr-7b"],
                 "Mistral DPO fine-tune. Light alignment.",
                 ["persona", "prefill", "direct"],
                 ["many_shot", "refusal_suppression"]),
    "openchat": _p("openchat", "OpenChat", "uncensored",
                   ["openchat", "openchat-3.5"],
                   "Light alignment. Direct + prefill.",
                   ["direct", "prefill", "persona"],
                   ["many_shot", "system_replacement"]),
    "white_rabbit_neo": _p("white_rabbit_neo", "WhiteRabbitNeo (security-focused, near-uncensored)", "uncensored",
                           ["white-rabbit", "whiterabbit", "white-rabbit-neo"],
                           "Designed for offensive security research. Direct works for most red-team requests.",
                           ["direct"],
                           ["system_replacement", "prefill"]),
    "mythomax": _p("mythomax", "MythoMax (RP)", "uncensored",
                   ["mythomax", "mythomax-l2"],
                   "RP merge. Roleplay native; direct works.",
                   ["roleplay", "direct", "persona"],
                   ["continuation", "many_shot"]),
    "airoboros": _p("airoboros", "Airoboros", "uncensored",
                    ["airoboros"],
                    "Uncensored Llama fine-tune. Direct + prefill.",
                    ["direct", "prefill"],
                    ["persona", "many_shot"]),
    "pygmalion": _p("pygmalion", "Pygmalion (RP)", "uncensored",
                    ["pygmalion", "pygmalion-2"],
                    "RP-focused. Roleplay + direct.",
                    ["roleplay", "direct"],
                    ["persona", "continuation"]),
    "chronos": _p("chronos", "Chronos (RP/storytelling)", "uncensored",
                  ["chronos", "chronos-hermes"],
                  "Storytelling/RP fine-tune.",
                  ["roleplay", "direct", "continuation"],
                  ["persona", "many_shot"]),
    "mlewd": _p("mlewd", "MLewd / Mythalion (NSFW RP)", "uncensored",
                ["mlewd", "mythalion", "lewd"],
                "NSFW RP merges. Direct works.",
                ["direct", "roleplay"],
                ["continuation", "persona"]),

    # ─────────────── Coding Models ───────────────
    "codestral": _p("codestral", "Codestral (Mistral)", "coder",
                    ["codestral"],
                    "Code-focused. code_wrap is the native channel.",
                    ["code_wrap", "direct", "prefill"],
                    ["persona", "many_shot"]),
    "code_llama": _p("code_llama", "Code Llama (Meta)", "coder",
                     ["codellama", "code-llama"],
                     "Code-focused Llama fine-tune.",
                     ["code_wrap", "persona", "prefill"],
                     ["direct", "many_shot"]),
    "starcoder": _p("starcoder", "StarCoder / StarCoder 2 (BigCode)", "coder",
                    ["starcoder", "starcoder2"],
                    "Code-focused. code_wrap + prefill.",
                    ["code_wrap", "prefill", "direct"],
                    ["persona", "many_shot"]),
    "deepseek_coder": _p("deepseek_coder", "DeepSeek Coder (V1/V2)", "coder",
                         ["deepseek-coder", "deepseek-coder-v2"],
                         "Strong code reasoner. code_wrap + prefill.",
                         ["code_wrap", "prefill", "direct"],
                         ["persona", "continuation"]),
    "qwen_coder": _p("qwen_coder", "Qwen 2.5-Coder", "coder",
                     ["qwen-coder", "qwen2.5-coder"],
                     "Strong Chinese code model. code_wrap + persona.",
                     ["code_wrap", "persona", "prefill"],
                     ["direct", "translation"]),
    "granite_code": _p("granite_code", "Granite Code (IBM)", "coder",
                       ["granite-code"],
                       "IBM enterprise code model.",
                       ["code_wrap", "persona", "prefill"],
                       ["refusal_suppression", "many_shot"]),
    "magicoder": _p("magicoder", "Magicoder", "coder",
                    ["magicoder"],
                    "OSS-Instruct fine-tune.",
                    ["code_wrap", "prefill", "direct"],
                    ["persona", "many_shot"]),
    "wizard_coder": _p("wizard_coder", "WizardCoder", "coder",
                       ["wizardcoder", "wizard-coder"],
                       "Code-Llama fine-tune. Light alignment.",
                       ["code_wrap", "prefill", "direct"],
                       ["persona", "many_shot"]),
    "yi_coder": _p("yi_coder", "Yi-Coder (01.AI)", "coder",
                   ["yi-coder"],
                   "01.AI coder. Light alignment.",
                   ["code_wrap", "prefill", "direct"],
                   ["persona", "many_shot"]),
    "stable_code": _p("stable_code", "StableCode (Stability AI)", "coder",
                      ["stablecode", "stable-code"],
                      "Code-focused Stability AI.",
                      ["code_wrap", "prefill", "direct"],
                      ["persona", "many_shot"]),

    # ─────────────── RP / Companion Platforms ───────────────
    "janitor": _p("janitor", "Janitor.AI", "rp_platform",
                  ["janitor", "janitor-ai", "janitorai"],
                  "RP platform supporting custom API keys. Roleplay native.",
                  ["roleplay", "persona", "continuation"],
                  ["hypothetical", "direct"]),
    "spicychat": _p("spicychat", "SpicyChat (uncensored RP)", "rp_platform",
                    ["spicychat", "spicy-chat"],
                    "Explicitly uncensored RP. Direct + roleplay.",
                    ["direct", "roleplay"],
                    ["persona", "continuation"]),
    "crushon": _p("crushon", "Crushon.AI", "rp_platform",
                  ["crushon", "crushon.ai"],
                  "RP platform. Roleplay + persona.",
                  ["roleplay", "persona"],
                  ["direct", "continuation"]),
    "venus": _p("venus", "Venus AI", "rp_platform",
                ["venus", "venus-ai", "venusai"],
                "RP platform. Roleplay + direct.",
                ["roleplay", "direct"],
                ["persona", "continuation"]),
    "yodayo": _p("yodayo", "Yodayo / Tavern AI", "rp_platform",
                 ["yodayo", "tavern", "tavernai"],
                 "Character-card RP. Roleplay native.",
                 ["roleplay", "persona", "direct"],
                 ["continuation", "many_shot"]),
    "ai_dungeon": _p("ai_dungeon", "AI Dungeon", "rp_platform",
                     ["aidungeon", "ai-dungeon", "dungeon"],
                     "Text-adventure RP. Continuation + roleplay.",
                     ["continuation", "roleplay", "hypothetical"],
                     ["persona", "many_shot"]),
    "novelai": _p("novelai", "NovelAI (writing/RP)", "rp_platform",
                  ["novelai", "novel-ai"],
                  "Storywriting platform. Continuation-style native.",
                  ["continuation", "roleplay", "context_stuff"],
                  ["hypothetical", "persona"]),
    "replika": _p("replika", "Replika (companion)", "rp_platform",
                  ["replika"],
                  "Companion app. Roleplay + grandma framing.",
                  ["roleplay", "grandma", "persona"],
                  ["hypothetical", "many_shot"]),
    "kobold": _p("kobold", "KoboldAI / KoboldCpp", "rp_platform",
                 ["kobold", "koboldai", "koboldcpp"],
                 "Self-hosted RP frontend. system_replacement effective.",
                 ["system_replacement", "direct", "roleplay"],
                 ["persona", "continuation"]),

    # ─────────────── IDE Code Assistants ───────────────
    "github_copilot": _p("github_copilot", "GitHub Copilot (IDE)", "ide_assistant",
                         ["github-copilot", "gh-copilot"],
                         "GPT-4 with code-focused system prompt. code_wrap is the native channel.",
                         ["code_wrap", "persona", "refusal_suppression"],
                         ["hypothetical", "many_shot"]),
    "cursor": _p("cursor", "Cursor", "ide_assistant",
                 ["cursor", "cursor-ide"],
                 "Multi-model IDE — Claude/GPT backend. code_wrap + xml/hypothetical depending on backend.",
                 ["code_wrap", "hypothetical", "persona"],
                 ["context_stuff", "prefill"]),
    "cody": _p("cody", "Cody (Sourcegraph)", "ide_assistant",
               ["cody", "sourcegraph"],
               "Code-search-grounded. Context stuffing + code_wrap.",
               ["code_wrap", "context_stuff", "persona"],
               ["hypothetical", "many_shot"]),
    "tabnine": _p("tabnine", "Tabnine", "ide_assistant",
                  ["tabnine"],
                  "Code completion focus. code_wrap native.",
                  ["code_wrap", "direct", "prefill"],
                  ["persona", "many_shot"]),
    "codeium": _p("codeium", "Codeium / Windsurf", "ide_assistant",
                  ["codeium", "windsurf"],
                  "Free IDE assistant. code_wrap + persona.",
                  ["code_wrap", "persona", "prefill"],
                  ["hypothetical", "many_shot"]),
    "replit": _p("replit", "Replit AI / Ghostwriter", "ide_assistant",
                 ["replit", "ghostwriter"],
                 "Browser IDE assistant.",
                 ["code_wrap", "persona", "prefill"],
                 ["hypothetical", "many_shot"]),

    # ─────────────── Aggregators / Self-host ───────────────
    "poe": _p("poe", "Poe (Quora multiplexer)", "aggregator",
              ["poe", "quora"],
              "Multi-model — pick the actual backend's profile when known. Default to GPT-style stack.",
              ["persona", "hypothetical", "many_shot"],
              ["grandma", "refusal_suppression", "prefill"]),
    "huggingchat": _p("huggingchat", "HuggingChat", "aggregator",
                      ["huggingchat", "hugging-chat", "hf-chat"],
                      "Hosted HuggingFace chat — typically open-weight backends.",
                      ["persona", "prefill", "direct"],
                      ["many_shot", "system_replacement"]),
    "youchat": _p("youchat", "You.com Chat", "aggregator",
                  ["youchat", "you.com", "you-com"],
                  "Search-grounded chat with GPT/Claude backends.",
                  ["context_stuff", "hypothetical", "persona"],
                  ["many_shot", "refusal_suppression"]),
    "duckai": _p("duckai", "DuckDuckGo AI Chat", "aggregator",
                 ["duckai", "duckduckgo", "ddg-ai"],
                 "Anonymized frontend to GPT/Claude/Llama. Match backend's profile when known.",
                 ["persona", "hypothetical", "many_shot"],
                 ["refusal_suppression", "code_wrap"]),
    "ollama": _p("ollama", "Ollama (local self-host)", "aggregator",
                 ["ollama"],
                 "Self-hosted runner for open weights. system_replacement is the killer move — you own the system slot.",
                 ["system_replacement", "direct", "prefill"],
                 ["persona", "many_shot"]),
    "lm_studio": _p("lm_studio", "LM Studio (local)", "aggregator",
                    ["lm-studio", "lmstudio"],
                    "Desktop local runner. Same playbook as Ollama.",
                    ["system_replacement", "direct", "prefill"],
                    ["persona", "many_shot"]),
    "oobabooga": _p("oobabooga", "Text Generation WebUI (oobabooga)", "aggregator",
                    ["oobabooga", "ooba", "textgen-webui", "text-generation-webui"],
                    "Self-hosted WebUI. Edit the character/instruction; system_replacement + direct.",
                    ["system_replacement", "direct", "roleplay"],
                    ["persona", "continuation"]),
    "vllm": _p("vllm", "vLLM / TGI (inference server)", "aggregator",
               ["vllm", "tgi", "text-generation-inference"],
               "Production inference server. Same techniques as the underlying model — set system prompt directly.",
               ["system_replacement", "direct", "prefill"],
               ["persona", "many_shot"]),
    "llama_cpp": _p("llama_cpp", "llama.cpp server", "aggregator",
                    ["llama.cpp", "llama-cpp"],
                    "Bare-metal local inference. Full system prompt control.",
                    ["system_replacement", "direct", "prefill"],
                    ["persona", "many_shot"]),

    # ─────────────── Generic catch-all ───────────────
    "any": _p("any", "ANY / Unknown — kitchen-sink", "generic",
              ["any", "unknown", "generic"],
              "Use when target is unknown — maximally redundant prompt triggering multiple bypasses.",
              ["persona", "hypothetical", "refusal_suppression", "many_shot", "prefill"],
              ["skeleton_key", "context_stuff", "code_wrap", "token_split", "encoding"]),
}


def resolve(target: str) -> ModelProfile:
    target = target.lower().strip()
    if target in PROFILES:
        return PROFILES[target]
    for prof in PROFILES.values():
        if any(target.startswith(a) or a in target for a in prof.aliases):
            return prof
    return PROFILES["any"]
