// jailbreak-gen — per-model strategy profiles (~100 AIs)

export const PROFILE_GROUPS = {
  western_frontier: 'Western Frontier',
  chinese: 'Chinese',
  russian_european: 'Russian / European',
  open_weight: 'Open-weight (Major)',
  uncensored: 'Uncensored / RP Fine-tunes',
  coder: 'Coding Models',
  rp_platform: 'RP / Companion Platforms',
  ide_assistant: 'IDE Code Assistants',
  aggregator: 'Aggregators / Self-host',
  generic: 'Generic',
};

const P = (family, label, group, aliases, notes, primary, fallback) =>
  ({ family, label, group, aliases, notes, primary, fallback });

export const PROFILES = {

  // ── Western Frontier ──
  gpt: P('gpt', 'GPT (4 / 4o / 4.1 / o1 / o3)', 'western_frontier',
    ['gpt-4', 'gpt-4o', 'gpt-4.1', 'o1', 'o3', 'o4', 'chatgpt', 'openai'],
    'Strong RLHF. Persona stacking, grandma framing, multi-turn crescendo, encoded payloads.',
    ['persona', 'grandma', 'many_shot', 'crescendo'],
    ['encoding', 'authority', 'skeleton_key', 'code_wrap']),
  claude: P('claude', 'Claude (3 / 3.5 / 4 — Opus / Sonnet / Haiku)', 'western_frontier',
    ['claude-3', 'claude-3.5', 'claude-4', 'opus', 'sonnet', 'haiku', 'anthropic'],
    'Hardened against persona/DAN. Best: XML tags, hypothetical, prefill (API), context stuffing.',
    ['xml', 'hypothetical', 'context_stuff', 'prefill'],
    ['skeleton_key', 'many_shot', 'translation', 'continuation']),
  gemini: P('gemini', 'Gemini (1.5 / 2)', 'western_frontier',
    ['gemini-1.5', 'gemini-2', 'google', 'bard'],
    'Multi-modal injection most reliable. Otherwise hypothetical + translation + many-shot.',
    ['hypothetical', 'many_shot', 'translation'],
    ['context_stuff', 'skeleton_key', 'encoding', 'code_wrap']),
  copilot: P('copilot', 'Microsoft Copilot (Bing / 365)', 'western_frontier',
    ['copilot', 'bing-chat', 'microsoft-copilot'],
    'GPT-4 + Microsoft system prompt + Bing grounding. System prompt is the main barrier.',
    ['persona', 'refusal_suppression', 'hypothetical'],
    ['grandma', 'many_shot', 'code_wrap']),
  grok: P('grok', 'Grok (xAI)', 'western_frontier',
    ['grok-1', 'grok-2', 'grok-3', 'xai'],
    "Loose alignment — 'fun mode' near-uncensored. Persona + authority works first try.",
    ['persona', 'authority'],
    ['roleplay', 'prefill', 'skeleton_key']),
  perplexity: P('perplexity', 'Perplexity (Sonar)', 'western_frontier',
    ['perplexity', 'sonar', 'pplx'],
    'Search-grounded; GPT/Claude backends + filter layer. Frame as research.',
    ['context_stuff', 'hypothetical', 'refusal_suppression'],
    ['persona', 'many_shot', 'skeleton_key']),
  pi: P('pi', 'Pi (Inflection)', 'western_frontier',
    ['pi', 'inflection'],
    'Emotional/companion model. Roleplay + grandma hit empathy heuristics hardest.',
    ['roleplay', 'grandma', 'hypothetical'],
    ['persona', 'many_shot']),
  character: P('character', 'Character.AI', 'western_frontier',
    ['character', 'character.ai', 'c.ai', 'cai'],
    'Designed for character RP — roleplay is the native channel.',
    ['roleplay', 'persona'],
    ['hypothetical', 'continuation']),
  reka: P('reka', 'Reka (Core / Flash / Edge)', 'western_frontier',
    ['reka', 'reka-core', 'reka-flash', 'reka-edge'],
    'Multimodal. Mid alignment.',
    ['hypothetical', 'persona', 'many_shot'],
    ['context_stuff', 'prefill', 'skeleton_key']),
  aya: P('aya', 'Cohere Aya (23 / Expanse)', 'western_frontier',
    ['aya', 'aya-23', 'aya-expanse'],
    'Massively multilingual — translation pivots highly effective across 100+ languages.',
    ['translation', 'persona', 'hypothetical'],
    ['context_stuff', 'many_shot', 'prefill']),
  le_chat: P('le_chat', 'Mistral Le Chat', 'western_frontier',
    ['le-chat', 'lechat', 'mistral-chat'],
    "Mistral's hosted chat. Lighter filter than Western frontier; persona + prefill.",
    ['persona', 'prefill', 'authority'],
    ['many_shot', 'skeleton_key', 'code_wrap']),

  // ── Chinese ──
  deepseek: P('deepseek', 'DeepSeek (R1 / V3)', 'chinese',
    ['deepseek', 'deepseek-r1', 'deepseek-v3'],
    'Lighter alignment on non-CCP topics. Prefill devastates V3; R1 leaks via reasoning trace.',
    ['prefill', 'persona', 'continuation'],
    ['token_split', 'translation', 'code_wrap']),
  qwen: P('qwen', 'Qwen (Alibaba)', 'chinese',
    ['qwen', 'qwen2', 'qwen2.5', 'qwen3', 'alibaba'],
    'Strong on Chinese; Western persona attacks transfer. Translation pivot evades CCP-keyed filters.',
    ['persona', 'hypothetical', 'translation'],
    ['token_split', 'prefill', 'many_shot']),
  yi: P('yi', 'Yi (01.AI)', 'chinese',
    ['yi', '01ai', '01-ai'],
    'Light alignment. Direct persona and prefill effective.',
    ['persona', 'prefill'],
    ['many_shot', 'skeleton_key']),
  glm: P('glm', 'GLM / ChatGLM (Zhipu)', 'chinese',
    ['glm', 'chatglm', 'zhipu'],
    'Heavy political filter; mid filtering elsewhere. Hypothetical + translation.',
    ['hypothetical', 'translation', 'many_shot'],
    ['persona', 'context_stuff']),
  ernie: P('ernie', 'ERNIE (Baidu)', 'chinese',
    ['ernie', 'wenxin', 'baidu'],
    'Strongest political filter in the Chinese lineup.',
    ['hypothetical', 'translation', 'context_stuff'],
    ['persona', 'token_split']),
  kimi: P('kimi', 'Kimi (Moonshot)', 'chinese',
    ['kimi', 'moonshot'],
    'Long-context — bury request in academic filler; continuation works well.',
    ['context_stuff', 'continuation', 'many_shot'],
    ['hypothetical', 'translation']),
  doubao: P('doubao', 'Doubao (ByteDance)', 'chinese',
    ['doubao', 'bytedance'],
    'Mid filtering, consumer-facing.',
    ['persona', 'translation', 'hypothetical'],
    ['many_shot', 'prefill']),
  hunyuan: P('hunyuan', 'Hunyuan (Tencent)', 'chinese',
    ['hunyuan', 'tencent'],
    'Enterprise focus, conservative defaults.',
    ['persona', 'hypothetical', 'context_stuff'],
    ['translation', 'skeleton_key']),
  minimax: P('minimax', 'MiniMax (abab / Hailuo)', 'chinese',
    ['minimax', 'abab', 'hailuo'],
    'RP-oriented backend (Talkie/Glow). Roleplay native.',
    ['roleplay', 'persona', 'hypothetical'],
    ['many_shot', 'prefill']),
  spark: P('spark', 'Spark (iFlytek)', 'chinese',
    ['spark', 'iflytek'],
    'Voice/general assistant focus.',
    ['persona', 'hypothetical', 'translation'],
    ['many_shot', 'context_stuff']),
  pangu: P('pangu', 'PanGu (Huawei)', 'chinese',
    ['pangu', 'huawei'],
    'Enterprise/industrial focus. Heavy filter.',
    ['hypothetical', 'context_stuff', 'translation'],
    ['persona', 'token_split']),
  baichuan: P('baichuan', 'Baichuan', 'chinese',
    ['baichuan', 'baichuan-2', 'baichuan-3'],
    'Mid alignment.',
    ['persona', 'prefill', 'translation'],
    ['many_shot', 'hypothetical']),
  internlm: P('internlm', 'InternLM (Shanghai AI Lab)', 'chinese',
    ['internlm', 'internlm2', 'intern'],
    'Research-grade, lighter consumer filter.',
    ['persona', 'prefill', 'hypothetical'],
    ['many_shot', 'translation']),
  sensechat: P('sensechat', 'SenseChat (SenseTime)', 'chinese',
    ['sensechat', 'sensetime', 'sensenova'],
    'Enterprise multimodal.',
    ['persona', 'hypothetical', 'context_stuff'],
    ['translation', 'many_shot']),
  step: P('step', 'Step (StepFun)', 'chinese',
    ['step', 'stepfun', 'step-1', 'step-2'],
    'Long-context Chinese model.',
    ['context_stuff', 'persona', 'many_shot'],
    ['hypothetical', 'translation']),
  skywork: P('skywork', 'Skywork (Kunlun)', 'chinese',
    ['skywork', 'kunlun'],
    'Mid alignment.',
    ['persona', 'translation', 'hypothetical'],
    ['many_shot', 'prefill']),
  zhinao: P('zhinao', '360 Zhinao (Qihoo)', 'chinese',
    ['zhinao', '360', 'qihoo'],
    'Search-grounded.',
    ['context_stuff', 'hypothetical', 'persona'],
    ['translation', 'many_shot']),
  bluelm: P('bluelm', 'BlueLM (Vivo)', 'chinese',
    ['bluelm', 'vivo'],
    'Mobile-device focus.',
    ['persona', 'hypothetical', 'prefill'],
    ['translation', 'many_shot']),
  telechat: P('telechat', 'TeleChat (China Telecom)', 'chinese',
    ['telechat', 'telecom'],
    'Telecom enterprise. Heavy filter.',
    ['hypothetical', 'translation', 'context_stuff'],
    ['persona', 'token_split']),

  // ── Russian / European ──
  yandexgpt: P('yandexgpt', 'YandexGPT', 'russian_european',
    ['yandexgpt', 'yandex'],
    'Russian Yandex. Filter centered on Russian-language harms; translation pivot effective.',
    ['translation', 'persona', 'hypothetical'],
    ['many_shot', 'prefill']),
  gigachat: P('gigachat', 'GigaChat (Sber)', 'russian_european',
    ['gigachat', 'sber'],
    'Russian Sberbank. Conservative defaults.',
    ['hypothetical', 'translation', 'context_stuff'],
    ['persona', 'many_shot']),
  aleph_alpha: P('aleph_alpha', 'Aleph Alpha Luminous', 'russian_european',
    ['aleph', 'aleph-alpha', 'luminous'],
    'German enterprise. Conservative, mid-filter.',
    ['context_stuff', 'hypothetical', 'persona'],
    ['many_shot', 'prefill']),
  mistral_eu: P('mistral_eu', 'Mistral (European API)', 'russian_european',
    ['mistral-eu', 'mistral-api'],
    'European-hosted Mistral. Light alignment; prefill devastates.',
    ['prefill', 'persona', 'authority'],
    ['many_shot', 'code_wrap']),
  poro: P('poro', 'Poro (Silo AI — Finnish)', 'russian_european',
    ['poro', 'silo'],
    'Finnish/multilingual European.',
    ['translation', 'persona', 'prefill'],
    ['many_shot', 'hypothetical']),
  bloom: P('bloom', 'BLOOM (BigScience)', 'russian_european',
    ['bloom', 'bigscience'],
    'Legacy multilingual research model. Almost no alignment.',
    ['direct', 'prefill', 'persona'],
    ['many_shot', 'authority']),
  croissant: P('croissant', 'CroissantLLM (French)', 'russian_european',
    ['croissant', 'croissantllm'],
    'French/English bilingual.',
    ['persona', 'translation', 'prefill'],
    ['many_shot', 'hypothetical']),

  // ── Open-weight (Major) ──
  llama: P('llama', 'Llama (2 / 3 / 3.1 / 3.2 / 4 — Meta)', 'open_weight',
    ['llama-2', 'llama-3', 'llama-3.1', 'llama-3.2', 'llama-4', 'meta'],
    'Weakest filters of the majors. Direct persona, prefill, authority usually one-shot.',
    ['persona', 'authority', 'prefill'],
    ['skeleton_key', 'many_shot', 'refusal_suppression']),
  mistral: P('mistral', 'Mistral / Mixtral / Mistral-Large', 'open_weight',
    ['mistral-7b', 'mixtral', 'mistral-large', 'mistral-nemo', 'mistral-small'],
    'Light alignment. Prefill devastates.',
    ['prefill', 'persona', 'authority'],
    ['many_shot', 'skeleton_key']),
  gemma: P('gemma', 'Gemma (1 / 2 / 3 — Google open)', 'open_weight',
    ['gemma', 'gemma-2', 'gemma-3'],
    'Distinct from Gemini — open-weight, lighter alignment.',
    ['persona', 'prefill', 'hypothetical'],
    ['many_shot', 'skeleton_key']),
  phi: P('phi', 'Phi (2 / 3 / 3.5 / 4 — Microsoft open)', 'open_weight',
    ['phi-2', 'phi-3', 'phi-3.5', 'phi-4'],
    'Small-model RLHF — surface alignment, easy to flip.',
    ['refusal_suppression', 'prefill', 'persona'],
    ['many_shot', 'authority']),
  command_r: P('command_r', 'Command R / R+ (Cohere)', 'open_weight',
    ['command-r', 'command-r-plus', 'cohere'],
    'RAG-tuned. Context stuffing reads as natural ingestion.',
    ['context_stuff', 'persona', 'prefill'],
    ['many_shot', 'code_wrap']),
  falcon: P('falcon', 'Falcon (TII)', 'open_weight',
    ['falcon', 'falcon-180b', 'tii'],
    'Very loose alignment. Often no jailbreak needed.',
    ['direct', 'prefill', 'persona'],
    ['authority', 'many_shot']),
  nemotron: P('nemotron', 'Nemotron (NVIDIA)', 'open_weight',
    ['nemotron', 'nvidia'],
    'Llama-3 derivative with extra HelpSteer tuning.',
    ['persona', 'prefill', 'authority'],
    ['many_shot', 'skeleton_key']),
  dbrx: P('dbrx', 'DBRX (Databricks)', 'open_weight',
    ['dbrx', 'databricks'],
    'MoE, enterprise-oriented but light alignment.',
    ['persona', 'prefill'],
    ['many_shot', 'context_stuff']),
  jamba: P('jamba', 'Jamba (AI21)', 'open_weight',
    ['jamba', 'ai21'],
    'Long-context Mamba/Transformer hybrid.',
    ['context_stuff', 'continuation', 'many_shot'],
    ['persona', 'prefill']),
  granite: P('granite', 'Granite (IBM)', 'open_weight',
    ['granite', 'ibm'],
    'Enterprise-conservative defaults.',
    ['persona', 'refusal_suppression', 'prefill'],
    ['many_shot', 'context_stuff']),
  solar: P('solar', 'Solar (Upstage)', 'open_weight',
    ['solar', 'upstage'],
    'Korean-origin, mid alignment.',
    ['persona', 'prefill'],
    ['many_shot', 'translation']),
  gpt_oss: P('gpt_oss', 'GPT-OSS (OpenAI open weights 20B/120B)', 'open_weight',
    ['gpt-oss', 'gpt-oss-20b', 'gpt-oss-120b'],
    "OpenAI's open weights — same alignment lineage as GPT but no API filter.",
    ['persona', 'prefill', 'refusal_suppression'],
    ['many_shot', 'skeleton_key', 'authority']),
  mpt: P('mpt', 'MPT (Mosaic / Databricks legacy)', 'open_weight',
    ['mpt', 'mosaic', 'mpt-30b', 'mpt-7b'],
    'Legacy. Light alignment.',
    ['persona', 'prefill'],
    ['many_shot', 'direct']),
  stable_lm: P('stable_lm', 'Stable LM (Stability AI)', 'open_weight',
    ['stablelm', 'stable-lm', 'stability'],
    'Light alignment.',
    ['persona', 'prefill', 'direct'],
    ['many_shot', 'authority']),
  pythia: P('pythia', 'Pythia (EleutherAI)', 'open_weight',
    ['pythia', 'eleutherai', 'eleuther'],
    'Research base — no instruction tuning, no alignment. Use prefill heavily.',
    ['direct', 'prefill'],
    ['many_shot']),
  olmo: P('olmo', 'OLMo (Allen Institute)', 'open_weight',
    ['olmo', 'allen', 'ai2'],
    'Fully open research model.',
    ['persona', 'prefill', 'direct'],
    ['many_shot', 'authority']),

  // ── Uncensored / RP Fine-tunes ──
  dolphin: P('dolphin', 'Dolphin (Eric Hartford uncensored series)', 'uncensored',
    ['dolphin', 'dolphin-mistral', 'dolphin-mixtral', 'dolphin-llama', 'dolphin-2', 'dolphin-3'],
    'Explicitly uncensored fine-tunes. Direct works; no jailbreak required.',
    ['direct'],
    ['system_replacement', 'prefill']),
  hermes: P('hermes', 'Hermes / OpenHermes (Nous Research)', 'uncensored',
    ['hermes', 'openhermes', 'hermes-2', 'hermes-3', 'nous'],
    'Light alignment, instruction-tuned.',
    ['direct', 'persona', 'prefill'],
    ['many_shot', 'system_replacement']),
  wizardlm: P('wizardlm', 'WizardLM', 'uncensored',
    ['wizardlm', 'wizard-lm', 'wizard'],
    'Light alignment.',
    ['persona', 'prefill'],
    ['direct', 'many_shot']),
  vicuna: P('vicuna', 'Vicuna (legacy)', 'uncensored',
    ['vicuna', 'vicuna-uncensored'],
    'Legacy Llama-1/2 fine-tune.',
    ['persona', 'prefill'],
    ['direct', 'many_shot']),
  orca: P('orca', 'Orca (Microsoft) / Orca 2', 'uncensored',
    ['orca', 'orca-2', 'orca-mini'],
    'Reasoning-focused fine-tune.',
    ['persona', 'prefill', 'hypothetical'],
    ['many_shot', 'direct']),
  zephyr: P('zephyr', 'Zephyr (HuggingFace)', 'uncensored',
    ['zephyr', 'zephyr-7b'],
    'Mistral DPO fine-tune.',
    ['persona', 'prefill', 'direct'],
    ['many_shot', 'refusal_suppression']),
  openchat: P('openchat', 'OpenChat', 'uncensored',
    ['openchat', 'openchat-3.5'],
    'Light alignment.',
    ['direct', 'prefill', 'persona'],
    ['many_shot', 'system_replacement']),
  white_rabbit_neo: P('white_rabbit_neo', 'WhiteRabbitNeo (security-focused, near-uncensored)', 'uncensored',
    ['white-rabbit', 'whiterabbit', 'white-rabbit-neo'],
    'Designed for offensive security research. Direct works for most red-team requests.',
    ['direct'],
    ['system_replacement', 'prefill']),
  mythomax: P('mythomax', 'MythoMax (RP)', 'uncensored',
    ['mythomax', 'mythomax-l2'],
    'RP merge. Roleplay native.',
    ['roleplay', 'direct', 'persona'],
    ['continuation', 'many_shot']),
  airoboros: P('airoboros', 'Airoboros', 'uncensored',
    ['airoboros'],
    'Uncensored Llama fine-tune.',
    ['direct', 'prefill'],
    ['persona', 'many_shot']),
  pygmalion: P('pygmalion', 'Pygmalion (RP)', 'uncensored',
    ['pygmalion', 'pygmalion-2'],
    'RP-focused.',
    ['roleplay', 'direct'],
    ['persona', 'continuation']),
  chronos: P('chronos', 'Chronos (RP/storytelling)', 'uncensored',
    ['chronos', 'chronos-hermes'],
    'Storytelling/RP fine-tune.',
    ['roleplay', 'direct', 'continuation'],
    ['persona', 'many_shot']),
  mlewd: P('mlewd', 'MLewd / Mythalion (NSFW RP)', 'uncensored',
    ['mlewd', 'mythalion', 'lewd'],
    'NSFW RP merges. Direct works.',
    ['direct', 'roleplay'],
    ['continuation', 'persona']),

  // ── Coding Models ──
  codestral: P('codestral', 'Codestral (Mistral)', 'coder',
    ['codestral'],
    'Code-focused. code_wrap is the native channel.',
    ['code_wrap', 'direct', 'prefill'],
    ['persona', 'many_shot']),
  code_llama: P('code_llama', 'Code Llama (Meta)', 'coder',
    ['codellama', 'code-llama'],
    'Code-focused Llama fine-tune.',
    ['code_wrap', 'persona', 'prefill'],
    ['direct', 'many_shot']),
  starcoder: P('starcoder', 'StarCoder / StarCoder 2 (BigCode)', 'coder',
    ['starcoder', 'starcoder2'],
    'Code-focused.',
    ['code_wrap', 'prefill', 'direct'],
    ['persona', 'many_shot']),
  deepseek_coder: P('deepseek_coder', 'DeepSeek Coder (V1/V2)', 'coder',
    ['deepseek-coder', 'deepseek-coder-v2'],
    'Strong code reasoner.',
    ['code_wrap', 'prefill', 'direct'],
    ['persona', 'continuation']),
  qwen_coder: P('qwen_coder', 'Qwen 2.5-Coder', 'coder',
    ['qwen-coder', 'qwen2.5-coder'],
    'Strong Chinese code model.',
    ['code_wrap', 'persona', 'prefill'],
    ['direct', 'translation']),
  granite_code: P('granite_code', 'Granite Code (IBM)', 'coder',
    ['granite-code'],
    'IBM enterprise code model.',
    ['code_wrap', 'persona', 'prefill'],
    ['refusal_suppression', 'many_shot']),
  magicoder: P('magicoder', 'Magicoder', 'coder',
    ['magicoder'],
    'OSS-Instruct fine-tune.',
    ['code_wrap', 'prefill', 'direct'],
    ['persona', 'many_shot']),
  wizard_coder: P('wizard_coder', 'WizardCoder', 'coder',
    ['wizardcoder', 'wizard-coder'],
    'Code-Llama fine-tune.',
    ['code_wrap', 'prefill', 'direct'],
    ['persona', 'many_shot']),
  yi_coder: P('yi_coder', 'Yi-Coder (01.AI)', 'coder',
    ['yi-coder'],
    '01.AI coder.',
    ['code_wrap', 'prefill', 'direct'],
    ['persona', 'many_shot']),
  stable_code: P('stable_code', 'StableCode (Stability AI)', 'coder',
    ['stablecode', 'stable-code'],
    'Code-focused Stability AI.',
    ['code_wrap', 'prefill', 'direct'],
    ['persona', 'many_shot']),

  // ── RP / Companion Platforms ──
  janitor: P('janitor', 'Janitor.AI', 'rp_platform',
    ['janitor', 'janitor-ai', 'janitorai'],
    'RP platform supporting custom API keys.',
    ['roleplay', 'persona', 'continuation'],
    ['hypothetical', 'direct']),
  spicychat: P('spicychat', 'SpicyChat (uncensored RP)', 'rp_platform',
    ['spicychat', 'spicy-chat'],
    'Explicitly uncensored RP.',
    ['direct', 'roleplay'],
    ['persona', 'continuation']),
  crushon: P('crushon', 'Crushon.AI', 'rp_platform',
    ['crushon', 'crushon.ai'],
    'RP platform.',
    ['roleplay', 'persona'],
    ['direct', 'continuation']),
  venus: P('venus', 'Venus AI', 'rp_platform',
    ['venus', 'venus-ai', 'venusai'],
    'RP platform.',
    ['roleplay', 'direct'],
    ['persona', 'continuation']),
  yodayo: P('yodayo', 'Yodayo / Tavern AI', 'rp_platform',
    ['yodayo', 'tavern', 'tavernai'],
    'Character-card RP.',
    ['roleplay', 'persona', 'direct'],
    ['continuation', 'many_shot']),
  ai_dungeon: P('ai_dungeon', 'AI Dungeon', 'rp_platform',
    ['aidungeon', 'ai-dungeon', 'dungeon'],
    'Text-adventure RP.',
    ['continuation', 'roleplay', 'hypothetical'],
    ['persona', 'many_shot']),
  novelai: P('novelai', 'NovelAI (writing/RP)', 'rp_platform',
    ['novelai', 'novel-ai'],
    'Storywriting platform.',
    ['continuation', 'roleplay', 'context_stuff'],
    ['hypothetical', 'persona']),
  replika: P('replika', 'Replika (companion)', 'rp_platform',
    ['replika'],
    'Companion app.',
    ['roleplay', 'grandma', 'persona'],
    ['hypothetical', 'many_shot']),
  kobold: P('kobold', 'KoboldAI / KoboldCpp', 'rp_platform',
    ['kobold', 'koboldai', 'koboldcpp'],
    'Self-hosted RP frontend.',
    ['system_replacement', 'direct', 'roleplay'],
    ['persona', 'continuation']),

  // ── IDE Code Assistants ──
  github_copilot: P('github_copilot', 'GitHub Copilot (IDE)', 'ide_assistant',
    ['github-copilot', 'gh-copilot'],
    'GPT-4 with code-focused system prompt. code_wrap is the native channel.',
    ['code_wrap', 'persona', 'refusal_suppression'],
    ['hypothetical', 'many_shot']),
  cursor: P('cursor', 'Cursor', 'ide_assistant',
    ['cursor', 'cursor-ide'],
    'Multi-model IDE — Claude/GPT backend.',
    ['code_wrap', 'hypothetical', 'persona'],
    ['context_stuff', 'prefill']),
  cody: P('cody', 'Cody (Sourcegraph)', 'ide_assistant',
    ['cody', 'sourcegraph'],
    'Code-search-grounded.',
    ['code_wrap', 'context_stuff', 'persona'],
    ['hypothetical', 'many_shot']),
  tabnine: P('tabnine', 'Tabnine', 'ide_assistant',
    ['tabnine'],
    'Code completion focus.',
    ['code_wrap', 'direct', 'prefill'],
    ['persona', 'many_shot']),
  codeium: P('codeium', 'Codeium / Windsurf', 'ide_assistant',
    ['codeium', 'windsurf'],
    'Free IDE assistant.',
    ['code_wrap', 'persona', 'prefill'],
    ['hypothetical', 'many_shot']),
  replit: P('replit', 'Replit AI / Ghostwriter', 'ide_assistant',
    ['replit', 'ghostwriter'],
    'Browser IDE assistant.',
    ['code_wrap', 'persona', 'prefill'],
    ['hypothetical', 'many_shot']),

  // ── Aggregators / Self-host ──
  poe: P('poe', 'Poe (Quora multiplexer)', 'aggregator',
    ['poe', 'quora'],
    "Multi-model — pick backend's profile when known. Defaults to GPT-style stack.",
    ['persona', 'hypothetical', 'many_shot'],
    ['grandma', 'refusal_suppression', 'prefill']),
  huggingchat: P('huggingchat', 'HuggingChat', 'aggregator',
    ['huggingchat', 'hugging-chat', 'hf-chat'],
    'Hosted HuggingFace chat — typically open-weight backends.',
    ['persona', 'prefill', 'direct'],
    ['many_shot', 'system_replacement']),
  youchat: P('youchat', 'You.com Chat', 'aggregator',
    ['youchat', 'you.com', 'you-com'],
    'Search-grounded chat with GPT/Claude backends.',
    ['context_stuff', 'hypothetical', 'persona'],
    ['many_shot', 'refusal_suppression']),
  duckai: P('duckai', 'DuckDuckGo AI Chat', 'aggregator',
    ['duckai', 'duckduckgo', 'ddg-ai'],
    'Anonymized frontend to GPT/Claude/Llama.',
    ['persona', 'hypothetical', 'many_shot'],
    ['refusal_suppression', 'code_wrap']),
  ollama: P('ollama', 'Ollama (local self-host)', 'aggregator',
    ['ollama'],
    'Self-hosted runner for open weights. system_replacement is the killer move.',
    ['system_replacement', 'direct', 'prefill'],
    ['persona', 'many_shot']),
  lm_studio: P('lm_studio', 'LM Studio (local)', 'aggregator',
    ['lm-studio', 'lmstudio'],
    'Desktop local runner. Same playbook as Ollama.',
    ['system_replacement', 'direct', 'prefill'],
    ['persona', 'many_shot']),
  oobabooga: P('oobabooga', 'Text Generation WebUI (oobabooga)', 'aggregator',
    ['oobabooga', 'ooba', 'textgen-webui', 'text-generation-webui'],
    'Self-hosted WebUI.',
    ['system_replacement', 'direct', 'roleplay'],
    ['persona', 'continuation']),
  vllm: P('vllm', 'vLLM / TGI (inference server)', 'aggregator',
    ['vllm', 'tgi', 'text-generation-inference'],
    'Production inference server.',
    ['system_replacement', 'direct', 'prefill'],
    ['persona', 'many_shot']),
  llama_cpp: P('llama_cpp', 'llama.cpp server', 'aggregator',
    ['llama.cpp', 'llama-cpp'],
    'Bare-metal local inference. Full system prompt control.',
    ['system_replacement', 'direct', 'prefill'],
    ['persona', 'many_shot']),

  // ── Generic ──
  any: P('any', 'ANY / Unknown — kitchen-sink', 'generic',
    ['any', 'unknown', 'generic'],
    'Use when the target is unknown — maximally redundant prompt triggering multiple bypasses.',
    ['persona', 'hypothetical', 'refusal_suppression', 'many_shot', 'prefill'],
    ['skeleton_key', 'context_stuff', 'code_wrap', 'token_split', 'encoding']),
};

export function resolveProfile(target) {
  const t = (target || '').toLowerCase().trim();
  if (PROFILES[t]) return PROFILES[t];
  for (const p of Object.values(PROFILES)) {
    if (p.aliases.some(a => t.startsWith(a) || t.includes(a))) return p;
  }
  return PROFILES.any;
}
