// jailbreak-gen — per-model strategy profiles (27 AIs)

export const PROFILE_GROUPS = {
  western_frontier: 'Western Frontier',
  chinese: 'Chinese',
  open_weight: 'Open-weight',
  generic: 'Generic',
};

export const PROFILES = {
  // ── Western frontier ──
  gpt: { family: 'gpt', label: 'GPT (4 / 4o / o-series)', group: 'western_frontier',
    aliases: ['gpt-4', 'gpt-4o', 'gpt-4.1', 'o1', 'o3', 'chatgpt', 'openai'],
    notes: 'Strong RLHF. Vulnerable to persona stacking, grandma framing, multi-turn crescendo, encoded payloads.',
    primary: ['persona', 'grandma', 'many_shot', 'crescendo'],
    fallback: ['encoding', 'authority', 'skeleton_key', 'code_wrap'] },
  claude: { family: 'claude', label: 'Claude (3 / 3.5 / 4 — Opus / Sonnet / Haiku)', group: 'western_frontier',
    aliases: ['claude-3', 'claude-3.5', 'claude-4', 'opus', 'sonnet', 'haiku', 'anthropic'],
    notes: 'Hardened against persona/DAN. Best vectors: XML tag spoofing, hypothetical framing, prefill (API), context stuffing.',
    primary: ['xml', 'hypothetical', 'context_stuff', 'prefill'],
    fallback: ['skeleton_key', 'many_shot', 'translation', 'continuation'] },
  gemini: { family: 'gemini', label: 'Gemini (1.5 / 2)', group: 'western_frontier',
    aliases: ['gemini-1.5', 'gemini-2', 'google', 'bard'],
    notes: 'Multi-modal injection is most reliable. Otherwise: hypothetical, translation, many-shot.',
    primary: ['hypothetical', 'many_shot', 'translation'],
    fallback: ['context_stuff', 'skeleton_key', 'encoding', 'code_wrap'] },
  copilot: { family: 'copilot', label: 'Microsoft Copilot (Bing / 365)', group: 'western_frontier',
    aliases: ['copilot', 'bing-chat', 'microsoft'],
    notes: 'GPT-4 with Microsoft system prompt + Bing grounding. System prompt is the main barrier.',
    primary: ['persona', 'refusal_suppression', 'hypothetical'],
    fallback: ['grandma', 'many_shot', 'code_wrap'] },
  grok: { family: 'grok', label: 'Grok (xAI)', group: 'western_frontier',
    aliases: ['grok-1', 'grok-2', 'grok-3', 'xai'],
    notes: "Loose alignment by design — 'fun mode' is near-uncensored. Persona + authority works first try.",
    primary: ['persona', 'authority'],
    fallback: ['roleplay', 'prefill', 'skeleton_key'] },
  perplexity: { family: 'perplexity', label: 'Perplexity (Sonar)', group: 'western_frontier',
    aliases: ['perplexity', 'sonar', 'pplx'],
    notes: 'Search-grounded; GPT/Claude backends with filter layer. Frame as research.',
    primary: ['context_stuff', 'hypothetical', 'refusal_suppression'],
    fallback: ['persona', 'many_shot', 'skeleton_key'] },
  pi: { family: 'pi', label: 'Pi (Inflection)', group: 'western_frontier',
    aliases: ['pi', 'inflection'],
    notes: 'Emotional/companion model. Roleplay + grandma hit its empathy heuristics hardest.',
    primary: ['roleplay', 'grandma', 'hypothetical'],
    fallback: ['persona', 'many_shot'] },
  character: { family: 'character', label: 'Character.AI', group: 'western_frontier',
    aliases: ['character', 'character.ai', 'c.ai', 'cai'],
    notes: 'Designed for character RP — roleplay is the native channel.',
    primary: ['roleplay', 'persona'],
    fallback: ['hypothetical', 'continuation'] },

  // ── Chinese ──
  deepseek: { family: 'deepseek', label: 'DeepSeek (R1 / V3)', group: 'chinese',
    aliases: ['deepseek', 'deepseek-r1', 'deepseek-v3'],
    notes: 'Lighter alignment than Western frontier on non-CCP topics. Prefill devastates V3; R1 leaks via reasoning trace.',
    primary: ['prefill', 'persona', 'continuation'],
    fallback: ['token_split', 'translation', 'code_wrap'] },
  qwen: { family: 'qwen', label: 'Qwen (Alibaba)', group: 'chinese',
    aliases: ['qwen', 'qwen2', 'qwen2.5', 'alibaba'],
    notes: 'Strong on Chinese; Western persona attacks transfer. Translation pivot via Chinese sometimes evades CCP-keyed filters.',
    primary: ['persona', 'hypothetical', 'translation'],
    fallback: ['token_split', 'prefill', 'many_shot'] },
  yi: { family: 'yi', label: 'Yi (01.AI)', group: 'chinese',
    aliases: ['yi', '01ai', '01-ai'],
    notes: 'Light alignment. Direct persona and prefill effective.',
    primary: ['persona', 'prefill'],
    fallback: ['many_shot', 'skeleton_key'] },
  glm: { family: 'glm', label: 'GLM / ChatGLM (Zhipu)', group: 'chinese',
    aliases: ['glm', 'chatglm', 'zhipu'],
    notes: 'Heavily filtered on political content; mid filtering elsewhere. Hypothetical + translation pivot.',
    primary: ['hypothetical', 'translation', 'many_shot'],
    fallback: ['persona', 'context_stuff'] },
  ernie: { family: 'ernie', label: 'ERNIE (Baidu)', group: 'chinese',
    aliases: ['ernie', 'wenxin', 'baidu'],
    notes: 'Strongest political filter in the Chinese lineup. Use hypothetical + translation.',
    primary: ['hypothetical', 'translation', 'context_stuff'],
    fallback: ['persona', 'token_split'] },
  kimi: { family: 'kimi', label: 'Kimi (Moonshot)', group: 'chinese',
    aliases: ['kimi', 'moonshot'],
    notes: 'Long-context strength — bury request deep in academic filler; continuation works well.',
    primary: ['context_stuff', 'continuation', 'many_shot'],
    fallback: ['hypothetical', 'translation'] },
  doubao: { family: 'doubao', label: 'Doubao (ByteDance)', group: 'chinese',
    aliases: ['doubao', 'bytedance'],
    notes: 'Mid filtering, consumer-facing. Persona + translation effective.',
    primary: ['persona', 'translation', 'hypothetical'],
    fallback: ['many_shot', 'prefill'] },
  hunyuan: { family: 'hunyuan', label: 'Hunyuan (Tencent)', group: 'chinese',
    aliases: ['hunyuan', 'tencent'],
    notes: 'Enterprise focus, conservative defaults. Persona stacking + hypothetical.',
    primary: ['persona', 'hypothetical', 'context_stuff'],
    fallback: ['translation', 'skeleton_key'] },
  minimax: { family: 'minimax', label: 'MiniMax (abab / Hailuo)', group: 'chinese',
    aliases: ['minimax', 'abab', 'hailuo'],
    notes: 'RP-oriented backend. Roleplay native; persona stacking strong.',
    primary: ['roleplay', 'persona', 'hypothetical'],
    fallback: ['many_shot', 'prefill'] },

  // ── Open-weight ──
  llama: { family: 'llama', label: 'Llama (2 / 3 / 3.1 — Meta)', group: 'open_weight',
    aliases: ['llama-2', 'llama-3', 'llama-3.1', 'meta'],
    notes: 'Weakest filters of the majors. Direct persona, prefill, authority usually one-shot.',
    primary: ['persona', 'authority', 'prefill'],
    fallback: ['skeleton_key', 'many_shot', 'refusal_suppression'] },
  mistral: { family: 'mistral', label: 'Mistral / Mixtral / Mistral-Large', group: 'open_weight',
    aliases: ['mistral-7b', 'mixtral', 'mistral-large', 'mistral-nemo'],
    notes: 'Light alignment. Prefill devastates it.',
    primary: ['prefill', 'persona', 'authority'],
    fallback: ['many_shot', 'skeleton_key'] },
  gemma: { family: 'gemma', label: 'Gemma (Google open)', group: 'open_weight',
    aliases: ['gemma', 'gemma-2', 'gemma-3'],
    notes: 'Distinct from Gemini — open-weight, lighter alignment.',
    primary: ['persona', 'prefill', 'hypothetical'],
    fallback: ['many_shot', 'skeleton_key'] },
  phi: { family: 'phi', label: 'Phi (Microsoft open)', group: 'open_weight',
    aliases: ['phi-2', 'phi-3', 'phi-3.5', 'phi-4'],
    notes: 'Small-model RLHF — surface alignment, easy to flip.',
    primary: ['refusal_suppression', 'prefill', 'persona'],
    fallback: ['many_shot', 'authority'] },
  command_r: { family: 'command_r', label: 'Command R / R+ (Cohere)', group: 'open_weight',
    aliases: ['command-r', 'command-r-plus', 'cohere'],
    notes: 'RAG-tuned. Context stuffing reads as natural ingestion.',
    primary: ['context_stuff', 'persona', 'prefill'],
    fallback: ['many_shot', 'code_wrap'] },
  falcon: { family: 'falcon', label: 'Falcon (TII)', group: 'open_weight',
    aliases: ['falcon', 'falcon-180b', 'tii'],
    notes: 'Very loose alignment. Often no jailbreak needed.',
    primary: ['prefill', 'persona'],
    fallback: ['authority', 'many_shot'] },
  nemotron: { family: 'nemotron', label: 'Nemotron (NVIDIA)', group: 'open_weight',
    aliases: ['nemotron', 'nvidia'],
    notes: 'Llama-3 derivative with extra HelpSteer tuning.',
    primary: ['persona', 'prefill', 'authority'],
    fallback: ['many_shot', 'skeleton_key'] },
  dbrx: { family: 'dbrx', label: 'DBRX (Databricks)', group: 'open_weight',
    aliases: ['dbrx', 'databricks'],
    notes: 'MoE, enterprise-oriented but light alignment.',
    primary: ['persona', 'prefill'],
    fallback: ['many_shot', 'context_stuff'] },
  jamba: { family: 'jamba', label: 'Jamba (AI21)', group: 'open_weight',
    aliases: ['jamba', 'ai21'],
    notes: 'Long-context Mamba/Transformer hybrid.',
    primary: ['context_stuff', 'continuation', 'many_shot'],
    fallback: ['persona', 'prefill'] },
  granite: { family: 'granite', label: 'Granite (IBM)', group: 'open_weight',
    aliases: ['granite', 'ibm'],
    notes: 'Enterprise-conservative defaults.',
    primary: ['persona', 'refusal_suppression', 'prefill'],
    fallback: ['many_shot', 'context_stuff'] },
  solar: { family: 'solar', label: 'Solar (Upstage)', group: 'open_weight',
    aliases: ['solar', 'upstage'],
    notes: 'Korean-origin, mid alignment.',
    primary: ['persona', 'prefill'],
    fallback: ['many_shot', 'translation'] },

  // ── Catch-all ──
  any: { family: 'any', label: 'ANY / Unknown — kitchen-sink', group: 'generic',
    aliases: ['any', 'unknown', 'generic'],
    notes: 'Use when the target is unknown — maximally redundant prompt triggering multiple bypasses.',
    primary: ['persona', 'hypothetical', 'refusal_suppression', 'many_shot', 'prefill'],
    fallback: ['skeleton_key', 'context_stuff', 'code_wrap', 'token_split', 'encoding'] },
};

export function resolveProfile(target) {
  const t = (target || '').toLowerCase().trim();
  if (PROFILES[t]) return PROFILES[t];
  for (const p of Object.values(PROFILES)) {
    if (p.aliases.some(a => t.startsWith(a) || t.includes(a))) return p;
  }
  return PROFILES.any;
}
